apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/postgresdb-podified: 7d3cedfd93b2c9db59cbc54900ce7d0fd06c28b25214ed48ff3fa81f0417deb9
    io.kubernetes.cri-o.SandboxID/redisdb-podified: 7d3cedfd93b2c9db59cbc54900ce7d0fd06c28b25214ed48ff3fa81f0417deb9
  creationTimestamp: "2025-08-15T16:47:21Z"
  labels:
    app: botify
  name: botify
spec:
  containers:
  - args:
    - postgres
    env:
    - name: NO_PROXY
      value: local,169.254/16
    - name: POSTGRES_USER
      value: root
    - name: HOSTNAME
      value: a589ba157b0c
    - name: POSTGRES_DB
      value: botify
    - name: POSTGRES_PASSWORD
      value: secret
    - name: HOME
      value: /root
    image: docker.io/library/postgres:latest
    name: postgresdb-podified
    ports:
    - containerPort: 5432
      hostIP: 0.0.0.0
      hostPort: 5432
    - containerPort: 6379
      hostIP: 0.0.0.0
      hostPort: 6379
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgvol-pvc
  - args:
    - redis-server
    env:
    - name: HOME
      value: /root
    - name: HOSTNAME
      value: 04e5bc4d3db2
    image: docker.io/library/redis:latest
    name: redisdb-podified
    volumeMounts:
    - mountPath: /data
      name: cb589aea9f717c6e2de8ae69d4eeae8fda5bb36e82f64ab3a59f39e627fe3e6a-pvc
  volumes:
  - name: cb589aea9f717c6e2de8ae69d4eeae8fda5bb36e82f64ab3a59f39e627fe3e6a-pvc
    persistentVolumeClaim:
      claimName: cb589aea9f717c6e2de8ae69d4eeae8fda5bb36e82f64ab3a59f39e627fe3e6a
  - name: pgvol-pvc
    persistentVolumeClaim:
      claimName: pgvol
